services:
  mongodb:
    image: mongo:6.0 
    container_name: chemical_db_container
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - chemicaldb_data:/data/db

  mongo-express:
    image: mongo-express:1.0
    container_name: mongo_express_container
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb

volumes:
  chemicaldb_data:
 